### ISSUE TITLE
Live activity

### ISSUE THREAD

**Issue by lucasnijssen** [wissehes/zermelo-app-ios#6]
Zou je miss live activity toe kunnen voegen? Zodat je bijvoorbeeld op je Dynamic Island je lokaal ziet en hoelang de les nog duurt?

**Comment by wissehes** [comment]
DIt zou inderdaad een hele coole feature zijn! Het probleem is alleen dat ik niet meer op de middelbare zit, en geen toegang meer heb tot zermelo en de app dus ook niet meer kan testen :( ik ben verder ook niet van plan de app nog meer te onderhouden

**Comment by lucasnijssen** [comment]
Wat jammer! Is het misschien mogelijk voor mij om de app proberen te updaten met die functie en dat jij hem dan online zet?
